name: "Workflow test"

on:
  pull_request:
    paths-ignore:
      - "**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout [Pull Request]
        if: ${{ github.event_name == 'pull_request' }}
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - uses: actions/checkout@v2
        name: Checkout [Push]
        if: ${{ github.event_name != 'pull_request' }}
        with:
          fetch-depth: 0

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install
        run: npm ci

      - name: Compile
        run: npm run build

      - name: Test default PR Workflow
        if: github.event_name == 'pull_request'
        uses: ./
        with:
          main-branch-name: ${{ github.base_ref }}
      - name: Verify default PR Workflow
        if: github.event_name == 'pull_request'
        shell: bash
        run: |
          BASE_SHA=$(echo $(git merge-base origin/${{github.base_ref}} HEAD))
          HEAD_SHA=$(git rev-parse HEAD)
          node -e "if(process.env.NX_BASE == '${BASE_SHA}') console.log('Base set correctly'); else { throw new Error('Base not set correctly!');}"
          node -e "if(process.env.NX_HEAD == '${HEAD_SHA}') console.log('Head set correctly'); else { throw new Error('Head not set correctly!');}"

      - name: Test default Push Workflow
        if: github.event_name != 'pull_request'
        uses: ./
        with:
          main-branch-name: ${{ github.ref_name }}
      - name: Verify default Push Workflow
        if: github.event_name != 'pull_request'
        shell: bash
        run: |
          BASE_SHA=$(echo $(git rev-parse HEAD~1))
          HEAD_SHA=$(echo $(git rev-parse HEAD))
          node -e "if(process.env.NX_BASE == '${BASE_SHA}') console.log('Base set correctly'); else { throw new Error('Base not set correctly!');}"
          node -e "if(process.env.NX_HEAD == '${HEAD_SHA}') console.log('Head set correctly'); else { throw new Error('Head not set correctly!');}"
